[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
bitcoin = "0.31"
bitcoincore-rpc = "0.18"
starknet = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
