[package]
name = "watcher-signer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hex = "0.4"
bitcoin = "0.31"
async-trait = "0.1"

[dev-dependencies]
common = { path = "../common", features = ["test-utils"] }
starknet = { workspace = true }
